// Sample storyboard scenes used by the "Add Sample Storyboard Scenes" button
// in the New Project flow. Local-only data, no APIs involved.

export const SAMPLE_SCENES = [
  {
    scene_number: 1,
    scene_title: 'Forest Beginning',
    story_text: 'A young hero walks through a glowing forest.',
    characters: ['Young Hero'],
    environment_description: 'Magical forest with soft light',
    camera_direction: 'Wide cinematic shot',
    image_prompt: 'Animated cartoon hero in a magical forest',
    animation_prompt: 'Slow camera push-in with gentle character movement',
    transition_to_next: 'fade',
    audio_mode: 'narration',
    narration_text: 'Once upon a time, a young hero entered a magical forest.',
    background_music_prompt: 'Soft magical forest music',
    sfx_prompt: 'Birds, wind, soft footsteps',
    voice_style: 'Warm storyteller',
    audio_timing: 0,
    duration: 6,
    visual_status: 'draft',
    audio_status: 'draft',
  },
  {
    scene_number: 2,
    scene_title: 'Hidden Cave',
    story_text: 'The hero discovers a hidden cave behind vines.',
    characters: ['Young Hero'],
    environment_description: 'Cave entrance hidden behind thick vines',
    camera_direction: 'Over-the-shoulder reveal',
    image_prompt: 'Animated cartoon hero discovering a hidden cave',
    animation_prompt: 'Camera reveals the cave as vines move gently',
    transition_to_next: 'cut',
    audio_mode: 'dialogue',
    dialogue_text: 'Young Hero: What is this place?',
    background_music_prompt: 'Curious magical music',
    sfx_prompt: 'Rustling vines, echo',
    voice_style: 'Curious childlike character voice',
    audio_timing: 6,
    duration: 6,
    visual_status: 'draft',
    audio_status: 'draft',
  },
];
