import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: (
      <p>By downloading, accessing, or using StudioOne Ai ("the App"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the App.</p>
    ),
  },
  {
    title: '2. AI Generation and Third-Party Services',
    content: (
      <>
        <p className="mb-3">StudioOne Ai utilizes various third-party artificial intelligence models (including but not limited to Runway ML, ElevenLabs, Suno AI, Meta AI, and others) to generate video, audio, and text.</p>
        <ul className="space-y-2">
          <li><span className="font-semibold">Third-Party Terms:</span> By using these generation features, you also agree to be bound by the respective Terms of Service of these third-party providers.</li>
          <li><span className="font-semibold">No Guarantee of Output:</span> Due to the nature of AI, we cannot guarantee the accuracy, appropriateness, or specific quality of the generated outputs.</li>
        </ul>
      </>
    ),
  },
  {
    title: '3. User-Generated Content and Intellectual Property',
    content: (
      <ul className="space-y-2">
        <li><span className="font-semibold">Ownership:</span> You retain ownership of the content you generate using the App, subject to the licensing terms of the specific third-party AI models used to create them.</li>
        <li><span className="font-semibold">Responsibility:</span> You are solely responsible for the content you create, download, and publish (including direct uploads to YouTube). You represent and warrant that you have the right to use any text prompts, reference images, or audio you input into the App.</li>
      </ul>
    ),
  },
  {
    title: '4. Prohibited Conduct',
    content: (
      <>
        <p className="mb-3">You agree <span className="font-semibold">NOT</span> to use StudioOne Ai to generate:</p>
        <ul className="space-y-2">
          <li><span className="font-semibold">Illegal Content:</span> Material that violates any local, national, or international law.</li>
          <li><span className="font-semibold">Hate Speech & Harassment:</span> Content that promotes discrimination, violence, or harassment against individuals or groups.</li>
          <li><span className="font-semibold">Deepfakes & Misinformation:</span> Deceptive audio or video content intended to mislead the public or impersonate real individuals without their explicit consent.</li>
          <li><span className="font-semibold">Copyright Infringement:</span> Content that violates the intellectual property rights, copyrights, or trademarks of others.</li>
        </ul>
      </>
    ),
  },
  {
    title: '5. Credits and Usage Limits',
    content: (
      <>
        <p className="mb-3">Certain features within the App require the use of internal credits.</p>
        <ul className="space-y-2">
          <li>Credits are consumed upon initiating a generation request, regardless of the final output quality.</li>
          <li>We reserve the right to suspend or terminate accounts that attempt to manipulate, hack, or abuse the credit system or our API integrations.</li>
        </ul>
      </>
    ),
  },
  {
    title: '6. Termination',
    content: (
      <p>We reserve the right to suspend or terminate your access to StudioOne Ai at any time, without prior notice or liability, for any reason, including if you breach these Terms and Conditions.</p>
    ),
  },
  {
    title: '7. Limitation of Liability',
    content: (
      <p>StudioOne Ai is provided on an "AS IS" and "AS AVAILABLE" basis. We shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the App, or from any content generated by the App.</p>
    ),
  },
  {
    title: '8. Contact Information',
    content: (
      <p>If you have any questions about these Terms, please contact us at: <a href="mailto:support@studioone-ai.com" className="text-primary underline underline-offset-2">support@studioone-ai.com</a></p>
    ),
  },
];

export default function TermsAndConditions() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-4 py-8">
        {/* Back Button */}
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate(-1)}
          className="mb-6 text-muted-foreground hover:text-foreground -ml-2"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>

        {/* Header */}
        <div className="mb-8">
          <h1 className="font-playfair text-3xl font-bold text-foreground mb-2">Terms and Conditions</h1>
          <p className="text-sm text-muted-foreground">Last Updated: May 10, 2026</p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((section) => (
            <div key={section.title} className="rounded-xl border border-border/50 bg-card p-5">
              <h2 className="font-playfair text-lg font-bold text-foreground mb-3">{section.title}</h2>
              <div className="text-sm text-muted-foreground leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2">
                {section.content}
              </div>
            </div>
          ))}
        </div>

        <p className="text-xs text-muted-foreground/50 text-center mt-10 mb-4">
          © 2026 StudioOne AI · Terms and Conditions
        </p>
      </div>
    </div>
  );
}