import { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { Download, FileText, Image, Music, Video, Film, Mic, FileCode, Lock, AlertTriangle } from 'lucide-react';
import { Link } from 'react-router-dom';

const EXPORT_DEFS = [
  {
    key: 'prompt_pack',
    label: 'Prompt Pack',
    desc: 'All visual + story prompts as a TXT file',
    icon: FileText,
    color: 'text-blue-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20',
    costKey: 'prompt_pack',
    requiresVideo: false,
    free: true,
  },
  {
    key: 'narration_script',
    label: 'Narration Script',
    desc: 'Full narration script per scene (TXT)',
    icon: Mic,
    color: 'text-teal-400',
    bg: 'bg-teal-500/10',
    border: 'border-teal-500/20',
    costKey: 'narration_script',
    requiresVideo: false,
    free: true,
  },
  {
    key: 'subtitles_srt',
    label: 'Subtitles (SRT)',
    desc: 'Auto-generated subtitle file from narration',
    icon: FileCode,
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/20',
    costKey: 'subtitles_srt',
    requiresVideo: false,
    free: false,
  },
  {
    key: 'storyboard_pdf',
    label: 'Storyboard PDF',
    desc: 'All scenes with images and prompts as PDF',
    icon: Film,
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/20',
    costKey: 'storyboard_pdf',
    requiresVideo: false,
    free: false,
  },
  {
    key: 'image_zip',
    label: 'Image Pack (ZIP)',
    desc: 'All approved scene images as a ZIP download',
    icon: Image,
    color: 'text-indigo-400',
    bg: 'bg-indigo-500/10',
    border: 'border-indigo-500/20',
    costKey: 'image_zip',
    requiresVideo: false,
    free: false,
  },
  {
    key: 'audio_zip',
    label: 'Audio Package (ZIP)',
    desc: 'All approved audio files as a ZIP download',
    icon: Music,
    color: 'text-green-400',
    bg: 'bg-green-500/10',
    border: 'border-green-500/20',
    costKey: 'audio_zip',
    requiresVideo: false,
    free: false,
  },
  {
    key: 'shorts_480p',
    label: 'Short Video (480p)',
    desc: 'Render final video in 480p MP4 — video provider required',
    icon: Video,
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/20',
    costKey: 'shorts_480p',
    requiresVideo: true,
    free: false,
  },
  {
    key: 'shorts_720p',
    label: 'Short Video (720p)',
    desc: 'Render final video in 720p MP4 — video provider required',
    icon: Video,
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/20',
    costKey: 'shorts_720p',
    requiresVideo: true,
    free: false,
  },
  {
    key: 'cinematic_1080p',
    label: 'Cinematic (1080p)',
    desc: 'Full cinematic render in 1080p — video provider required',
    icon: Film,
    color: 'text-rose-400',
    bg: 'bg-rose-500/10',
    border: 'border-rose-500/20',
    costKey: 'cinematic_1080p',
    requiresVideo: true,
    free: false,
  },
];

function downloadTextFile(content, filename) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadSRT(content, filename) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// Client-side PDF rendering using jsPDF
async function renderStoryboardPDF(data) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', format: 'a4' });

  doc.setFontSize(22);
  doc.text(data.project_title || 'Storyboard', 20, 25);
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`${data.project_type || ''} · Generated by StudioOne AI`, 20, 33);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 39);

  let y = 52;

  for (const scene of data.scenes) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    doc.text(`Scene ${scene.scene_number}${scene.approved ? ' ✓' : ''}`, 20, y);
    y += 6;

    if (scene.image_url) {
      try {
        // We skip actual image loading in PDF for performance — show placeholder info
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 200);
        doc.text(`[Image: ${scene.image_url.slice(0, 60)}...]`, 22, y);
        y += 5;
      } catch {}
    }

    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(scene.visual_prompt || '—', 170);
    const maxLines = Math.min(lines.length, 6);
    doc.text(lines.slice(0, maxLines), 22, y);
    y += maxLines * 4.5 + 8;
    doc.setDrawColor(220, 220, 220);
    doc.line(20, y - 4, 190, y - 4);
  }

  doc.save(`${data.project_title || 'storyboard'}_storyboard.pdf`);
}

export default function ExportDownloadCenter({ project, user, isAdmin, status, scenes, images, audioJobs, videoJobs, onRefresh }) {
  const [exporting, setExporting] = useState({});

  const costs = status?.costs || {};
  const balance = user?.gems_balance ?? 0;

  const handleExport = async (exportDef) => {
    if (exportDef.requiresVideo) {
      toast('Video rendering provider not configured yet. Stay tuned!', { icon: '🔧', duration: 4000 });
      return;
    }

    const gemCost = costs[exportDef.costKey] ?? 0;
    if (gemCost > 0 && balance < gemCost) {
      toast.error(`Not enough gems. Need ${gemCost}💎, have ${balance}💎.`);
      return;
    }

    setExporting(p => ({ ...p, [exportDef.key]: true }));
    try {
      const res = await base44.functions.invoke('exportPipeline', {
        action: 'export',
        project_id: project.id,
        export_type: exportDef.key,
      });

      const data = res.data;

      if (!data.success) {
        if (data.provider_not_configured) {
          toast('Provider not configured yet.', { icon: '🔧', duration: 4000 });
        } else {
          toast.error(data.error || 'Export failed');
        }
        return;
      }

      // Handle client-side downloads
      if (data.content) {
        downloadTextFile(data.content, data.filename || `${exportDef.key}.txt`);
        toast.success(`${exportDef.label} downloaded!`);
      } else if (data.type === 'client_render_pdf') {
        await renderStoryboardPDF(data);
        toast.success('Storyboard PDF generated!');
      } else if (data.type === 'image_list') {
        // Show links panel
        toast.success(`${data.images.length} approved images ready. Opening in new tab...`);
        const content = data.images.map(i => `Scene ${i.scene_number}: ${i.image_url}`).join('\n');
        downloadTextFile(content, `${project.title || 'images'}_image_urls.txt`);
      } else if (data.type === 'audio_list') {
        const content = data.audio.map(j => `Scene ${j.scene_number} [${j.action_type}]: ${j.audio_url}`).join('\n');
        downloadTextFile(content, `${project.title || 'audio'}_audio_urls.txt`);
        toast.success(`${data.audio.length} audio files listed. Download the TXT for URLs.`);
      }

      await onRefresh();
    } catch (e) {
      toast.error(e.message || 'Export failed');
    }
    setExporting(p => ({ ...p, [exportDef.key]: false }));
  };

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-sm font-bold text-foreground">Download Center</h3>
        <p className="text-xs text-muted-foreground mt-0.5">Export your project assets in various formats</p>
      </div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {EXPORT_DEFS.map(def => {
          const gemCost = costs[def.costKey] ?? 0;
          const isExporting = exporting[def.key];
          const canAfford = gemCost === 0 || balance >= gemCost;

          return (
            <div
              key={def.key}
              className={`rounded-xl border ${def.border} bg-card/30 p-4 flex flex-col gap-3`}
            >
              <div className="flex items-start gap-3">
                <div className={`w-9 h-9 rounded-lg ${def.bg} flex items-center justify-center shrink-0`}>
                  <def.icon className={`w-4 h-4 ${def.color}`} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className="text-sm font-semibold text-foreground">{def.label}</p>
                    {def.requiresVideo && (
                      <Badge variant="outline" className="text-[9px] border-border/30 text-muted-foreground">
                        Needs Render Provider
                      </Badge>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground mt-0.5">{def.desc}</p>
                </div>
              </div>

              <div className="flex items-center justify-between gap-2 mt-auto">
                <span className="text-xs text-muted-foreground">
                  {gemCost === 0 ? 'Free' : `${gemCost}💎`}
                </span>
                {def.requiresVideo ? (
                  <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                    <AlertTriangle className="w-3.5 h-3.5 text-amber-500/60" />
                    <span>Provider not configured</span>
                  </div>
                ) : !canAfford ? (
                  <Link to="/upgrade">
                    <Button size="sm" variant="outline" className="h-7 text-xs gap-1 border-border/40">
                      <Lock className="w-3 h-3" /> Get Gems
                    </Button>
                  </Link>
                ) : (
                  <Button
                    size="sm"
                    onClick={() => handleExport(def)}
                    disabled={isExporting}
                    className={`h-7 text-xs gap-1.5 ${def.requiresVideo ? 'opacity-40 cursor-not-allowed' : ''}`}
                  >
                    {isExporting ? (
                      <span className="w-3.5 h-3.5 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                    ) : (
                      <Download className="w-3.5 h-3.5" />
                    )}
                    {isExporting ? 'Exporting...' : 'Export'}
                  </Button>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <div className="flex items-start gap-2 p-3 rounded-xl bg-amber-500/5 border border-amber-500/20 text-xs text-amber-400/80">
        <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
        <span>Video rendering (480p / 720p / 1080p) requires a render provider (FFmpeg pipeline or cloud worker). These will be available in a future update.</span>
      </div>
    </div>
  );
}